title: Max J. Hilgenberg's Home
description: <em>To think is easy. To act is hard. But the hardest thing in the world is to act in accordance with your thinking.</em> - Johann Wolfgang von GÃ¶the
logo: /images/mhilgen_frame.png
show_downloads: true
theme: jekyll-theme-minimal
